### PR TITLE
Update release branch to 2.4

### PR DESCRIPTION
**Pull request by JakobGray**
Signed-off-by: Jakob Gray <20209054+JakobGray@users.noreply.github.com>

### CODE REVIEW

**Review by chrisahl — COMMENTED** [review]
Are you sure RELEASE_FF_BRANCH and RELEASE_MAIN_BRANCH are not needed anymore?

**Comment by hanqiuzh** [comment]
@chrisahl  yes, those files are for old build-harness fast-forward, and chart is using installer's fast-forward github action

**Comment by KevinFCormier** [comment]
Duplicated by https://github.com/open-cluster-management/console-chart/pull/150
Closing.

**Pull request closed without merging**
