### PR TITLE
Ingress upgrade to networking.k8s.io/v1

### PR DESCRIPTION
**Pull request by chrisahl**
Signed-off-by: Chris Ahl <cahl@redhat.com>

For issue https://github.com/open-cluster-management/backlog/issues/10925

### CODE REVIEW

**Comment by chrisahl** [comment]
/hold
need to test first

**Comment by chrisahl** [comment]
@haoqing0110 Are these changes what you are looking for?

**Comment by haoqing0110** [comment]
@chrisahl yes, thanks, lgtm!

**Comment by chrisahl** [comment]
I ran a test on OCP 4.7 and 2.3.0-SNAPSHOT-2021-04-14-13-45-05 and the new chart installed.
```
NAME: console-chart
LAST DEPLOYED: Wed Apr 14 13:07:46 2021
NAMESPACE: open-cluster-management
STATUS: deployed
REVISION: 1
TEST SUITE: None

```

**Review by Randy424 — APPROVED** [review]

**Pull request merged**
