### PR TITLE
use release-2.2 branch in clusterimageset subscription

### PR DESCRIPTION
**Pull request by ldpliu**
https://github.com/open-cluster-management/backlog/issues/17849

### CODE REVIEW

**Comment by jnpacker** [comment]
@ldpliu 2.2 and 2.3 are going to both use this until we release the z stream for 2.3. I suspect we have more customers on 2.3 then 2.2, so it might make sense to set `main` to the release-2.3 imageSets.  At least until the z-stream patch is released.  Thoughts??

**Comment by ldpliu** [comment]
@jnpacker Yes, you are right, we have set the main branch [clusterimageset](https://github.com/open-cluster-management/acm-hive-openshift-releases/tree/main/clusterImageSets/fast) directory config to release-2.3. So before the 2.3 z-stream patched, the current user will not be affected.

For this pr, we already sync the clusterimageset images in acm-hiveopenshift-release [release-2.2 branch](https://github.com/open-cluster-management/acm-hive-openshift-releases/tree/release-2.2/clusterImageSets/fast).  So we should also use the release-2.2 branch in console-chart. Actually, we also do the same thing in 2.3/2.4 branches.

**Review by jnpacker — APPROVED** [review]

**Pull request merged**
